spring.application.name=auth-service
server.port=8081

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/authDb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


authms.jwt.secret-key=${JWT_SECRET:default_secret_key}
authms.jwt.access-token-expiration-ms=604800000
authms.jwt.refresh-token-expiration-ms=2592000000
authms.jwt.issuer=authms

authms.otp.expiration-minutes=5
authms.otp.length=6
authms.otp.max-request-per-hour=5

authms.email.base-url=${EMAIL_BASE_URL:http://localhost:8082}
authms.email.from-address=noreply@myapp.com
authms.email.from-name=MyApp Support
authms.email.magic-link-expiration-minutes=15

authms.oauth2.google.client-id=${GOOGLE_CLIENT_ID}
authms.oauth2.google.client-secret=${GOOGLE_CLIENT_SECRET}

authms.security.service-keys=${SERVICE_KEYS:dev-service-key-replace-in-production}

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.com.authms=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate=WARN


